apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: primary-cluster-storage
spec:
  cluster: primary-cluster
  role: storage
  jvm:
    memory:
      heapSize: 512m
    args:
      - "-Dwith.http=false"
      - "-Dprimary.cluster=primary-cluster"
      - "-Dcoherence.distributed.threads.min=10"
  ports:
    - name: metrics
      port: 9612
      serviceMonitor:
        enabled: true
  coherence:
    cacheConfig: cache-config.xml
    metrics:
      enabled: true
  image: coherence-demo:4.0.1-SNAPSHOT
  imagePullPolicy: Always
  replicas: 2
---
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: primary-cluster-http
spec:
  cluster: primary-cluster
  role: http
  jvm:
    memory:
      heapSize: 512m
    args:
      - "-Dprimary.cluster=primary-cluster"
      - "-Dcoherence.management.http=inherit"
      - "-Dcoherence.management.http.port=30000"
      - "-Dcoherence.distributed.threads.min=10"
  ports:
    - name: http
      port: 8080
    - name: metrics
      port: 9612
      serviceMonitor:
        enabled: true
    - name: management
      port: 30000
  coherence:
    cacheConfig: cache-config.xml
    storageEnabled: false
    metrics:
      enabled: true
      port: 9612
  image: coherence-demo:4.0.1-SNAPSHOT
  imagePullPolicy: Always
  replicas: 1
