# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven - Snapshots

on:
  push:
    branches:
    - '*'
  schedule:
    # Every day at midnight
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coherenceVersion:
          - 23.09.3-SNAPSHOT
          - 23.09.1
          - 23.09.2

    steps:
    - uses: actions/checkout@v4


    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Print Versions
      run: mvn -version && ant -version

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-snapshots

    - name: Build and Verify
      env:
        COH_VERSION: ${{ matrix.coherenceVersion }}
      shell: bash
      run: |
        echo "Running verify against $COH_VERSION"
        mvn --file pom.xml -nsu --batch-mode -e -Dcoherence.version=$COH_VERSION clean install

    - name: Coherence Demo Jar
      uses: actions/upload-artifact@v4
      with:
        name: coherence-demo-jar
        path: target/coherence-demo-*.jar

    - name: Coherence Demo Javadoc
      uses: actions/upload-artifact@v4
      with:
        name: coherence-demo-javadoc
        path: target/coherence-demo-*-javadoc.jar
