# This workflow runs the polyglot demo

name: Java CI Polyglot Clients

on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Print Versions
      run: mvn -version && ant -version

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-snapshots

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml -Dcoherence.version=24.03
        mvn exec:exec > output.log 2>&1 &
        sleep 30

    - name: Test Go Client
      run: |
        pwd
        cd clients/go
        go get github.com/oracle/coherence-go-client@latest
        go build -o go-demo .
        ./go-demo size
        ./go-demo add-trades ORCL 1000
        ./go-demo stock-split ORCL 2
        ./go-demo monitor &
        PID=$!
        sleep 10 && kill -9 $PID
        cd ..

    - name: Test JavaScript Client
      run: |
        pwd
        cd clients/js
        npm install
        node main.js size
        node main.js add-trades DELL 1000
        node main.js stock-split DELL 2
        node main.js monitor &
        PID=$!
        sleep 10 && kill -9 $PID
        cd ..

    - name: Test Python Client
      run: |
        pwd
        cd clients/py
        python3 -m pip install coherence-client
        python3 main.py size
        python3 main.py add-trades MSFT 1000
        python3 main.py stock-split MSFT 2
        python3 main.py monitor &
        PID=$!
        sleep 10 && kill -9 $PID
        cd ..