# This workflow runs the polyglot demo

name: Java CI Polyglot Clients

on:
  push:
    branches: [ "1412" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        javaVersion:
          - 21
          - 22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.javaVersion }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.javaVersion }}'
          distribution: 'zulu'

      - name: Print Versions
        run: mvn -version && ant -version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-snapshots

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml -Dcoherence.version=24.09
          echo "Running Coherence"
          mvn exec:exec > output.log 2>&1 &
          echo "Sleeping 30..."
          sleep 30
          tail -100 output.log

      - name: Test Go Client
        run: |
          pwd
          cd clients/go
          go get github.com/oracle/coherence-go-client/v2@latest
          go build -o go-demo .
          ./go-demo size
          ./go-demo add-trades ORCL 1000
          ./go-demo stock-split ORCL 2
          ./go-demo monitor &
          PID=$!
          sleep 10 && kill -9 $PID
          cd ..

      - name: Test JavaScript Client
        run: |
          pwd
          cd clients/js
          npm install
          node main.js size
          node main.js add-trades DELL 1000
          node main.js stock-split DELL 2
          node main.js monitor &
          PID=$!
          sleep 10 && kill -9 $PID
          cd ..

      - name: Test Python Client
        run: |
          pwd
          cd clients/py
          python3 -m pip install coherence-client
          python3 main.py size
          python3 main.py add-trades MSFT 1000
          python3 main.py stock-split MSFT 2
          python3 main.py monitor &
          PID=$!
          sleep 10 && kill -9 $PID
          cd ..